name: Internship Monitor

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore cached last_readme
        uses: actions/cache@v3
        id: cache
        with:
          path: last_readme.md
          key: internship-readme-cache

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run monitor script
        env:
          FROM_EMAIL_ADDRESS: ${{ secrets.FROM_EMAIL_ADDRESS }}
          FROM_EMAIL_PASSWORD: ${{ secrets.FROM_EMAIL_PASSWORD }}
          TO_EMAIL_ADDRESS: ${{ secrets.TO_EMAIL_ADDRESS }}
        run: python monitor.py

      - name: Save cached last_readme
        uses: actions/cache@v3
        with:
          path: last_readme.md
          key: internship-readme-cache
